# Generated by Django 4.2.1 on 2023-05-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='parent',
        ),
        migrations.AddField(
            model_name='blog',
            name='build_indicator_link',
            field=models.ManyToManyField(blank=True, db_index=True, to='core.blog'),
        ),
        migrations.AddField(
            model_name='blog',
            name='build_table_link',
            field=models.ManyToManyField(blank=True, db_index=True, to='core.blog'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='categories',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='%(app_label)s_%(class)s_category', to='core.category', verbose_name='Categories'),
        ),
    ]
