# Generated by Django 4.2.1 on 2023-05-10 11:03

from django.db import migrations
# import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_blog_parent_blog_build_indicator_link_and_more'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='blog',
        #     name='countries',
        #     field=django_countries.fields.CountryField(blank=True, db_index=True, max_length=746, multiple=True),
        # ),
    ]
