# Generated by Django 4.2.1 on 2023-05-10 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_blog_countries'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='blog',
        #     name='countries',
        # ),
    ]
