# Generated by Django 4.2.1 on 2023-05-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_blog_countries'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='job_area',
            field=models.CharField(choices=[('EU_COUNTRIES', 'EU_COUNTRIES'), ('AFRICAN_COUNTRIES', 'AFRICAN_COUNTRIES'), ('MIDDLEEAST_COUNTRIES', 'MIDDLEEAST_COUNTRIES'), ('OCENIA_COUNTRIES', 'OCENIA_COUNTRIES'), ('AMERICAN_COUNTRIES', 'AMERICAN_COUNTRIES'), ('ASIAN_COUNTRIES', 'ASIAN_COUNTRIES')], default='EU_COUNTRIES', max_length=20),
        ),
        migrations.AddField(
            model_name='blog',
            name='post_block',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blog',
            name='salary_block',
            field=models.BooleanField(default=False),
        ),
    ]
