# Generated by Django 4.2.1 on 2023-05-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_blog_job_area_blog_post_block_blog_salary_block'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='post_block',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='salary_block',
        ),
        migrations.AlterField(
            model_name='blog',
            name='job_area',
            field=models.CharField(choices=[('JOB_POST', 'JOB_POST'), ('SALARY_RANGE_BLOCK', 'SALARY_RANGE_BLOCK')], default='JOB_POST', max_length=20),
        ),
    ]
