# Generated by Django 4.2.1 on 2023-05-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_blog_extra_blocks_alter_blog_job_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='ref_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='job_area',
            field=models.CharField(choices=[('MIDDLEEAST_COUNTRIES', 'MIDDLEEAST_COUNTRIES'), ('EU_COUNTRIES', 'EU_COUNTRIES'), ('AMERICAN_COUNTRIES', 'AMERICAN_COUNTRIES'), ('ASIAN_COUNTRIES', 'ASIAN_COUNTRIES'), ('AFRICAN_COUNTRIES', 'AFRICAN_COUNTRIES'), ('OCENIA_COUNTRIES', 'OCENIA_COUNTRIES')], default='EU_COUNTRIES', max_length=20),
        ),
    ]
