# Generated by Django 4.2.1 on 2023-05-10 15:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_blog_extra_blocks_alter_blog_job_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='cv_library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_and_surename', models.CharField(max_length=252)),
                ('current_profession', models.CharField(max_length=252)),
                ('job_title_applying_for', models.CharField(max_length=252)),
                ('email_address', models.EmailField(max_length=254)),
                ('cv_file', models.FileField(upload_to='cv_files/', validators=[django.core.validators.FileExtensionValidator(['pdf'], message='Only PDF files are allowed.'), django.core.validators.MaxValueValidator(5242880, message='Maximum 5MB allowed')])),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='extra_blocks',
            field=models.CharField(choices=[('JOB_POST', 'JOB_POST'), ('SALARY_RANGE_BLOCK', 'SALARY_RANGE_BLOCK')], default='JOB_POST', max_length=20),
        ),
        migrations.AlterField(
            model_name='blog',
            name='job_area',
            field=models.CharField(choices=[('MIDDLEEAST_COUNTRIES', 'MIDDLEEAST_COUNTRIES'), ('OCENIA_COUNTRIES', 'OCENIA_COUNTRIES'), ('AMERICAN_COUNTRIES', 'AMERICAN_COUNTRIES'), ('EU_COUNTRIES', 'EU_COUNTRIES'), ('ASIAN_COUNTRIES', 'ASIAN_COUNTRIES'), ('AFRICAN_COUNTRIES', 'AFRICAN_COUNTRIES')], default='EU_COUNTRIES', max_length=20),
        ),
    ]
