# Generated by Django 4.2.1 on 2023-05-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_cv_library_cvlibrary_alter_blog_extra_blocks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='job_area',
            field=models.CharField(choices=[('EU_COUNTRIES', 'EU_COUNTRIES'), ('AMERICAN_COUNTRIES', 'AMERICAN_COUNTRIES'), ('AFRICAN_COUNTRIES', 'AFRICAN_COUNTRIES'), ('MIDDLEEAST_COUNTRIES', 'MIDDLEEAST_COUNTRIES'), ('ASIAN_COUNTRIES', 'ASIAN_COUNTRIES'), ('OCENIA_COUNTRIES', 'OCENIA_COUNTRIES')], default='EU_COUNTRIES', max_length=20),
        ),
    ]
