# Generated by Django 4.2.1 on 2023-05-11 05:40

import django.contrib.sites.managers
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('core', '0014_alter_blog_job_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExSite',
            fields=[
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sites.site', verbose_name='site')),
                ('site_meta', models.CharField(max_length=256)),
                ('site_description', models.TextField(max_length=500)),
                ('site_meta_tag', models.CharField(max_length=255)),
                ('site_favicon', models.ImageField(upload_to='site_image/')),
                ('site_logo', models.ImageField(upload_to='site_image/')),
                ('slogan', models.CharField(default='', max_length=150)),
                ('og_image', models.ImageField(upload_to='site_image/')),
                ('mask_icon', models.FileField(upload_to='site_image/', validators=[django.core.validators.FileExtensionValidator(['svg'])])),
                ('facebook_link', models.URLField()),
                ('twitter_link', models.URLField()),
                ('linkedin_link', models.URLField()),
            ],
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('on_site', django.contrib.sites.managers.CurrentSiteManager('site')),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='extra_blocks',
            field=models.CharField(choices=[('JOB_POST', 'JOB_POST'), ('SALARY_RANGE_BLOCK', 'SALARY_RANGE_BLOCK')], default='JOB_POST', max_length=20),
        ),
        migrations.AlterField(
            model_name='blog',
            name='job_area',
            field=models.CharField(choices=[('AMERICAN_COUNTRIES', 'AMERICAN_COUNTRIES'), ('OCENIA_COUNTRIES', 'OCENIA_COUNTRIES'), ('MIDDLEEAST_COUNTRIES', 'MIDDLEEAST_COUNTRIES'), ('AFRICAN_COUNTRIES', 'AFRICAN_COUNTRIES'), ('ASIAN_COUNTRIES', 'ASIAN_COUNTRIES'), ('EU_COUNTRIES', 'EU_COUNTRIES')], default='EU_COUNTRIES', max_length=20),
        ),
    ]
