# Generated by Django 4.2.1 on 2023-05-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_category_banner2_alter_blog_extra_blocks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='category',
            name='banner2',
        ),
        migrations.AlterField(
            model_name='blog',
            name='job_area',
            field=models.CharField(choices=[('OCENIA_COUNTRIES', 'OCENIA_COUNTRIES'), ('EU_COUNTRIES', 'EU_COUNTRIES'), ('MIDDLEEAST_COUNTRIES', 'MIDDLEEAST_COUNTRIES'), ('AFRICAN_COUNTRIES', 'AFRICAN_COUNTRIES'), ('AMERICAN_COUNTRIES', 'AMERICAN_COUNTRIES'), ('ASIAN_COUNTRIES', 'ASIAN_COUNTRIES')], default='EU_COUNTRIES', max_length=20),
        ),
    ]
