# Generated by Django 4.2.1 on 2023-05-12 00:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_responsebackup_alter_blog_job_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='should_as_it_is',
            field=models.BooleanField(default=False, verbose_name='Should As it is As Body?'),
        ),
        migrations.AddField(
            model_name='blog',
            name='should_have_apf',
            field=models.BooleanField(default=True, verbose_name='Should have Application Form?'),
        ),
        migrations.AddField(
            model_name='blog',
            name='should_have_hta',
            field=models.BooleanField(default=True, verbose_name='Should have How To Apply?'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='extra_blocks',
            field=models.CharField(choices=[('SALARY_RANGE_BLOCK', 'SALARY_RANGE_BLOCK'), ('JOB_POST', 'JOB_POST')], default='JOB_POST', max_length=20),
        ),
        migrations.AlterField(
            model_name='blog',
            name='job_area',
            field=models.CharField(choices=[('OCENIA_COUNTRIES', 'OCENIA_COUNTRIES'), ('MIDDLEEAST_COUNTRIES', 'MIDDLEEAST_COUNTRIES'), ('ASIAN_COUNTRIES', 'ASIAN_COUNTRIES'), ('AFRICAN_COUNTRIES', 'AFRICAN_COUNTRIES'), ('EU_COUNTRIES', 'EU_COUNTRIES'), ('AMERICAN_COUNTRIES', 'AMERICAN_COUNTRIES')], default='EU_COUNTRIES', max_length=20),
        ),
        migrations.AlterField(
            model_name='cvlibrary',
            name='cv_file',
            field=models.FileField(upload_to='cv_files/', validators=[django.core.validators.FileExtensionValidator(['pdf'], message='Only PDF files are allowed.'), django.core.validators.MaxValueValidator(5242880, message='Maximum 5MB allowed')], verbose_name='Upload your CV PDF only'),
        ),
    ]
