# Generated by Django 4.2.1 on 2023-05-12 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_action_ip_address_action_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='total_likes',
        ),
        migrations.RemoveField(
            model_name='action',
            name='total_views',
        ),
        migrations.AddField(
            model_name='action',
            name='action_type',
            field=models.CharField(choices=[('view', 'View'), ('like', 'Like')], default='view', max_length=4),
        ),
        migrations.AddField(
            model_name='action',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='job_area',
            field=models.CharField(choices=[('MIDDLEEAST_COUNTRIES', 'MIDDLEEAST_COUNTRIES'), ('AMERICAN_COUNTRIES', 'AMERICAN_COUNTRIES'), ('AFRICAN_COUNTRIES', 'AFRICAN_COUNTRIES'), ('ASIAN_COUNTRIES', 'ASIAN_COUNTRIES'), ('EU_COUNTRIES', 'EU_COUNTRIES'), ('OCENIA_COUNTRIES', 'OCENIA_COUNTRIES')], default='EU_COUNTRIES', max_length=20),
        ),
    ]
