# Generated by Django 4.2.1 on 2023-05-14 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_blog_creator_alter_blog_extra_blocks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='job_area',
            field=models.CharField(choices=[('AFRICAN_COUNTRIES', 'AFRICAN_COUNTRIES'), ('MIDDLEEAST_COUNTRIES', 'MIDDLEEAST_COUNTRIES'), ('AMERICAN_COUNTRIES', 'AMERICAN_COUNTRIES'), ('EU_COUNTRIES', 'EU_COUNTRIES'), ('ASIAN_COUNTRIES', 'ASIAN_COUNTRIES'), ('OCENIA_COUNTRIES', 'OCENIA_COUNTRIES')], default='EU_COUNTRIES', max_length=20),
        ),
        migrations.AlterField(
            model_name='cvlibrary',
            name='cv_file',
            field=models.FileField(upload_to='cv_files/', verbose_name='Upload your CV PDF only'),
        ),
    ]
