# Generated by Django 4.2.1 on 2023-05-14 05:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_blog_job_area_alter_cvlibrary_cv_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='job_area',
            field=models.CharField(choices=[('AFRICAN_COUNTRIES', 'AFRICAN_COUNTRIES'), ('EU_COUNTRIES', 'EU_COUNTRIES'), ('MIDDLEEAST_COUNTRIES', 'MIDDLEEAST_COUNTRIES'), ('ASIAN_COUNTRIES', 'ASIAN_COUNTRIES'), ('OCENIA_COUNTRIES', 'OCENIA_COUNTRIES'), ('AMERICAN_COUNTRIES', 'AMERICAN_COUNTRIES')], default='EU_COUNTRIES', max_length=20),
        ),
        migrations.AlterField(
            model_name='cvlibrary',
            name='cv_file',
            field=models.FileField(upload_to='cv_files/', validators=[django.core.validators.FileExtensionValidator(['pdf'], message='Only PDF files are allowed.'), django.core.validators.MaxValueValidator(5242880, message='Maximum 5MB allowed')], verbose_name='Upload your CV PDF only'),
        ),
    ]
