# Generated by Django 4.2.1 on 2023-05-15 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('core', '0038_alter_blog_extra_blocks_alter_blog_job_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action_type',
            field=models.CharField(choices=[('view', 'View'), ('like', 'Like')], db_index=True, default='view', max_length=4),
        ),
        migrations.AlterField(
            model_name='blog',
            name='extra_blocks',
            field=models.CharField(choices=[('JOB_POST', 'JOB_POST'), ('SALARY_RANGE_BLOCK', 'SALARY_RANGE_BLOCK')], default='JOB_POST', max_length=20),
        ),
        migrations.AlterField(
            model_name='blog',
            name='job_area',
            field=models.CharField(choices=[('AMERICAN_COUNTRIES', 'AMERICAN_COUNTRIES'), ('OCENIA_COUNTRIES', 'OCENIA_COUNTRIES'), ('MIDDLEEAST_COUNTRIES', 'MIDDLEEAST_COUNTRIES'), ('ASIAN_COUNTRIES', 'ASIAN_COUNTRIES'), ('AFRICAN_COUNTRIES', 'AFRICAN_COUNTRIES'), ('EU_COUNTRIES', 'EU_COUNTRIES')], default='EU_COUNTRIES', max_length=20),
        ),
        migrations.AlterField(
            model_name='blog',
            name='sites',
            field=models.ManyToManyField(db_index=True, related_name='%(app_label)s_%(class)s_sites', to='sites.site'),
        ),
        migrations.AlterField(
            model_name='category',
            name='sites',
            field=models.ManyToManyField(db_index=True, related_name='%(app_label)s_%(class)s_sites', to='sites.site'),
        ),
        migrations.AlterField(
            model_name='page',
            name='sites',
            field=models.ManyToManyField(db_index=True, related_name='%(app_label)s_%(class)s_sites', to='sites.site'),
        ),
        migrations.AlterField(
            model_name='responsebackup',
            name='key',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
