# Generated by Django 4.2.1 on 2023-05-29 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociateAt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Page Title')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='Slug')),
                ('is_active', models.BooleanField(default=True)),
                ('add_to_page_menu', models.BooleanField(default=False)),
                ('add_to_header_menu', models.BooleanField(default=False)),
                ('add_to_footer_menu', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_url', models.URLField()),
                ('creator', models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_creator', to=settings.AUTH_USER_MODEL)),
                ('sites', models.ManyToManyField(db_index=True, related_name='%(app_label)s_%(class)s_sites', to='sites.site')),
            ],
            options={
                'verbose_name': 'Associate At',
                'verbose_name_plural': 'All Associates',
                'ordering': ['-created_at'],
            },
        ),
    ]
