# Generated by Django 4.2.1 on 2023-05-19 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='title',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
