# Generated by Django 4.2.1 on 2023-05-19 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('createblog', '0002_topic_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['-id'], 'verbose_name': 'Topic', 'verbose_name_plural': 'Topics'},
        ),
        migrations.CreateModel(
            name='Outline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outline', models.TextField()),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createblog.topic')),
            ],
            options={
                'verbose_name': 'Outline',
                'verbose_name_plural': 'Outlines',
                'ordering': ['-id'],
            },
        ),
    ]
