# Generated by Django 4.2.1 on 2023-05-20 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('createblog', '0003_alter_topic_options_outline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outline',
            options={'ordering': ['id'], 'verbose_name': 'Outline', 'verbose_name_plural': 'Outlines'},
        ),
        migrations.CreateModel(
            name='DraftBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outline_id', models.BigIntegerField()),
                ('response', models.TextField()),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createblog.topic')),
            ],
            options={
                'verbose_name': 'Draft Blog',
                'verbose_name_plural': 'Draft Blogs',
                'ordering': ['id'],
            },
        ),
    ]
